### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices 

### ISSUE THREAD

**Issue by PoffDev** [RMukerjee416/launch#1]
On mobile things don't look as good as they could be. 

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile. 

Good luck researching and happy coding!

**Comment by RMukerjee416** [comment]
Hey Josh,

Thanks for the tip! I did some research and added the following in the header of "application.html.erb" of the Splurty folder: `<meta name="viewport" content="width=device-width, initial-scale=0.86, maximum-scale=3.0, minimum-scale=0.86">`

Apparently, the viewport needs to be manipulated for the elements of the webpage to be more visible on a mobile phone. I hope this helps the appearance (at least in terms of not having to zoom in)!

Thanks

**Comment by RMukerjee416** [comment]
No further comments, so I will close this issue.
Cheers!
